### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by fengzhang427** [zhangyi-3/noise-synthesis#4]
I have tested the results of camera s6 with the released checkpoints, but the psnr of camera s6 is only 20.13. I have executed the command exactly according to the readme. 
Would you help to check if there is a problem with the released checkpoints?
![image](https://user-images.githubusercontent.com/67069761/160088563-6192ce5d-e451-4adc-af94-4149b1b1a911.png)

**Comment by zhangyi-3** [comment]
Thanks for your question. I've tested the code and it works well. Can you provide your environment?
