### ISSUE TITLE
Performance gap between paper and ELD paper

### ISSUE THREAD

**Issue by wanglixilinx** [zhangyi-3/noise-synthesis#5]
Hi, @zhangyi-3,
   thanks very much for your work. I just have a question, as shown in Table 3,  the performance of SonyA7S2 with Ratio=100/200 in ELD[29] method is PSNR/SSIM=47.77/0.970, which is inconsistent with the accuracy in the ELD paper (PSNR/SSIM=45.36/0.972).

**Comment by zhangyi-3** [comment]
Thanks for your question.
Maybe, the main difference here is the training setting. We train and evaluate the model with a more wide range of ratios (1-200) instead of the ratios (100-200) used in ELD.
