### ISSUE TITLE
The bit-width of input image

### ISSUE THREAD

**Issue by m0yoshimura** [zhangyi-3/noise-synthesis#9]
Thank you very much for sharing your great work!
What bit-width should I use for input image in the bellow code especially for Sony a7s2 and Nikon D850?
It seems the noise models are not for images of 0~1 range.

https://github.com/zhangyi-3/noise-synthesis/blob/ee3ae273762fa5378cd2c8a6cc8d065560dd3cdb/synthesize.py#L21

**Comment by zhangyi-3** [comment]
Thanks for your question. The bit depth of them should be 14.

**Comment by m0yoshimura** [comment]
Thank you!
I will try to use it.

**Comment by fkmajiji** [comment]
Sorry for not opening a new issue. If I use iphone image as the input of def noise_profiles, should I normalize the value of image to range 0~1 or bit14 (0~16383)？

**Comment by fkmajiji** [comment]
Sorry for not opening a new issue. If I use iphone image as the input of def noise_profiles, should I normalize the value of image to range 0-1 or bit14 (0-16383)？

**Comment by fkmajiji** [comment]
Sorry for not opening a new issue. If I use iphone image as the input of def pg_noise_demo, should I normalize the value of image to range 0-1 or bit14 (0-16383)？
